var TEXT_SCORE = "SCORE";
var TEXT_CREDITS_DEVELOPED ="DEVELOPED BY";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";
var TEXT_HELP = "CLICK AND HOLD TO INCREASE THE JUMP STRENGTH, RELEASE TO BOUNCE";
var TEXT_BEST_SCORE = "BEST SCORE";
var TEXT_YOUR_SCORE = "FINAL SCORE";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Chog Cross - Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My Chog Cross score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";
